site_name: Telegram Automation Documentation

nav:
  - Home: docs/index.md
  - Installation: docs/installation.md
  - Usage: docs/usage.md
  - Backend API Docs: docs/backend_api_docs.md
  - Backend Code Docs (Sphinx): ../backend/docs/build/html/index.html



