site_name: Telegram Automation Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Documentation:
    - Backend API Docs: backend_api_docs.md
  - Docstring Best Practices: docstring_best_practices.md

