site_name: Telegram Automation Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Backend API Docs: backend_api_docs.md
  - Backend Code Docs (Sphinx): ../backend/docs/build/html/index.html



