site_name: Telegram Automation Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Documentation:
    - Backend API Docs: backend_api_docs.md
    - Backend Code Docs (Sphinx): backend_sphinx_html/index.html
    - Frontend Code Docs (JSDoc): frontend_jsdoc/index.html
  - Docstring Best Practices: docstring_best_practices.md

